name: Build editor

# Relevant sources:
# - https://game.ci/

on:
  push:
  pull_request:
    branches: [ develop ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    # We use the Windows runner because there are compile errors in the Ubuntu runner
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**', 'Structure/**') }}
          restore-keys: |
            Library- 

      - name: Build project
        uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          # The unity email and password can be found in the 'Game assets' vault of:
          # - https://vaultwarden.faforever.com/#
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          
          # The unity license is generated by the Unity Hub application:
          # - (1) Log in to the Unity account of FAForever
          # - (2) Go to the properties
          # - (3) Go to the licenses tab
          # - (4) Add a new personal license
          # - (5) The generated license can be found in C:\ProgramData\Unity\Unity_lic.ulf
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: FAForeverMapEditor
          versioning: Tag
          unityVersion: 2022.3.26f1

      - name: Add the Structure Directory to the Built Project
        shell: bash
        run: |
          mv ./Structure build/StandaloneWindows64/FAForeverMapEditor_Data/

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: FAForever Map Editor ${{ steps.buildStep.outputs.buildVersion || github.sha.substring(0, 7) }} Windows
          path: build/StandaloneWindows64

      - name: Add Build to Release
        if: github.event_name == 'release'
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          7z a FAForever.Map.Editor.${{ steps.buildStep.outputs.buildVersion }}.Windows.zip build/StandaloneWindows64
          gh release upload ${{ github.event.release.tag_name }} FAForever.Map.Editor.${{ steps.buildStep.outputs.buildVersion }}.Windows.zip

